dist: bionic
language: php

php:
    - '7.4'

services:
    - mysql

before_install:
    - php -i

install:
    - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction

script:
    - vendor/bin/phpstan analyze ./src --level 5 --memory-limit 1G
    - vendor/bin/phpunit --coverage-clover clover.xml --debug

after_script:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover clover.xml